from .queue_nodes import (
    NODE_CLASS_MAPPINGS as QUEUE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as QUEUE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .smart_fill_crop_resize_node import (
    NODE_CLASS_MAPPINGS as IMAGE_PREP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_PREP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .task_agent_core.nodes import (
    NODE_CLASS_MAPPINGS as TASK_AGENT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TASK_AGENT_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(TASK_AGENT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(QUEUE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMAGE_PREP_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(TASK_AGENT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(QUEUE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_PREP_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
